### PR TITLE
v6.0.4 with old propagation model deprecation

### PR DESCRIPTION
**Pull request by SergeAstapov**
v6.0.4 can be published from this branch per release plan #116

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@lukemelia could you please create `v6` branch (I can't create new branches in ember-keyboard)?

I believe we should publish those changes in this branch as v6.0.4 to land last deprecation to be good citizens (this branch has #499 minus breaking changes targeting v7 like #492)

**Comment by lukemelia** [comment]
Merged manually and released as 6.0.4

**Comment by SergeAstapov** [comment]
Thanks @lukemelia!

Although #492 still seem leaked into v6.0.4 https://github.com/adopted-ember-addons/ember-keyboard/releases/tag/v6.0.4 :/

**Comment by lukemelia** [comment]
Weird. Not sure how that happened. Let's roll with it and we'll cut 6.0.5 reverting that change if anyone needs it.

**Pull request closed without merging**
